# Generated by Django 3.1.1 on 2020-11-10 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listing',
            new_name='Birthday',
        ),
    ]
